### ISSUE TITLE
Low-level data vs. higher level metrics

### ISSUE THREAD

**Issue by igrigorik** [WICG/frame-timing#11]
One of the discussions at TPAC was around usefulness/actionability of low-level frame timing data exposed by Frame Timing. Should we be providing some higher-level metrics instead? A related concern was that processing this low-level data in client code might create its own perf bottlenecks, which would be unfortunate. 

On the other hand, there was no consensus in the room on what the "high level metrics" should be: averages are mostly harmful; min/median/max are slightly better but also require some arbitrary moving window; should we provide a setMark/measure interface to aggregate stats for a certain period of time?

Alternatively, what if we did both? The benefit of providing low-level data is that developers who know what they're doing can get high-fidelity access to measure performance of specific animations, scrolling, etc, which is not something we can "automagically" instrument. At the same time, providing some higher level rollups would allow easy integration for analytics + monitoring tools -- these metrics might not be perfect, but they can serve as good indicators of whether you have a render perf problem, or not.

`</crazy ideas>`

**Comment by paullewis** [comment]
> Should we be providing some higher-level metrics instead?

I personally don't think so, I think a JS-based library would make a lot of sense here, because any version of this that gets put in the spec will only work for a subset of use-cases. Getting all the data at least allows a developer to start digging in, and ideally a library can capture common cases (CSS animations, JS-based animations) and hooks to start and stop measurement.

> A related concern was that processing this low-level data in client code might create its own perf bottlenecks, which would be unfortunate.

Is there any room for having some form of transferable so a worker can do the data processing off the main thread?

I'm up for us adding higher level abstractions to the API if it's needed, although personally I would have thought a future iteration would make sense once we know the exact ways in which people are using the low-level data.

**Comment by igrigorik** [comment]
> I'm up for us adding higher level abstractions to the API if it's needed, although personally I would have thought a future iteration would make sense once we know the exact ways in which people are using the low-level data.

Personally, I'm on board with that, but there was a legitimate concern in the room that most developers simply wouldn't know what to do with this data... And, if the answer is "go install this JS library", then why are we not providing this functionality out of the gate? 

Resource-Timing serves as a good case study here.. It's been out for a while, but few people use it because it requires client-side processing and additional smarts -- as a result, analytics vendors are hesitant to automatically collect this data, and developers don't really know what to do with it either.

**Comment by mithro** [comment]
I very much against trying to add higher level data in the **initial** specification as I think it will only delay the much needed primitives. 

The "[Extensible Web Manifesto](https://extensiblewebmanifesto.org/)" makes a very strong argument that we should be providing the primitives first.

I also think we **don't** have a good understanding of what high level metrics would **actually** be useful (especially to web developers). The "Explainer" document does start to explore the space, but it really is only a start. With the current set of primitives specified, there is a great foundation for javascript libraries to quickly explore the space and provide examples. (With the extraordinary speed of modern Javascript until real world data shows actual performance is problem I don't think we should jump to conclusions about it.) Once we have this understanding we can then look at what the correct way to move forward is. This could be an updated version of the specification which includes them or even another specification that builds on this one.

I'd like to propose we make "high level metrics" an explicit **non**-goal of the V1 specification and agree to revisit it after that is completed. 

Have I missed something? I don't know much about Resource-Timing case here. I can try and get some real world data about the usage for the Resource-Timing features if that helps. A quick straw poll (3 non-Google and 8 Googler) seemed to indicate they all were already tracking or had intention of doing so "when they fix bigger issues".

**Comment by paullewis** [comment]
> if the answer is "go install this JS library", then why are we not providing this functionality out of the gate?

I think because we simply don't know what high level abstractions to create. I agree with @mithro that we actively shouldn't pursue too much for v1. I get the Resource-Timing concerns, but on the other side WebGL has Three.js, which is now the de-facto way to create WebGL content. Of course one could bake that stuff in (as one could with jQuery or any other library) but it reduces flexibility and opportunities to improve and iterate.

There should be a good companion library to come with the API that we can actively iterate on and attempt to encapsulate what we _think_ will be the common use-cases. So I wouldn't advocate a ship-and-hope approach here with the API, but rather I would argue we should have the low level API and something in "user space", i.e. JS, that we can use to actively and collectively find use-cases and make it easier for developers to use. I would personally be happy to work on that.

**Comment by igrigorik** [comment]
@mithro @paullewis I'm 100% with you on exposing the primitives, that's what I argued for as well. However, I'm just relaying the feedback from others in the room (Jason (IE) and Ryosuke (Safari) in particular), where they questioned the current API from two angles: (1) most developers won't know what to do with this data, (2) delivering data at this granularity can easily become its own performance problem, both for the UA, and for the developer trying to process it.
- We need to think about (2) from UA's perspective: can we deliver this data in a way that won't affect performance of the page? We're talking about emitting a lot of events. I think some concrete implementation data would go a long way here. 
  - @mpb can we get some overhead numbers from your current implementation?
- We need to think about (2) from developers perspective: what kind of guidance and/or tools can we provide to the developer to make sure that they don't shoot themselves in the foot by subscribing to this firehose.
- For (1), I think a better argument (instead of "we don't know what we need yet") is to document some use cases that rely on access to low-level data and don't share a common set of higher-level primitives, thus showing that you need the lower level instrumentation.

---

Speaking of API,  this is slightly orthogonal to above, but still relevant... What if instead of filling up a global buffer, we provided something closer to [mark](http://www.w3.org/TR/user-timing/#dom-performance-mark) and [measure](http://www.w3.org/TR/user-timing/#dom-performance-measure) functionality.. That is, in my code I set a starting point, and then indicate an ending point (e.g. start and end of animation), at which time I'd get access to the accumulate buffer of timing events between those markers + (optional) set of methods on that buffer to extract some aggregates (number of missed frames, median cputime per frame, whatever)? 

One benefit of above approach is that you can run multiple measurements in parallel without clearing the buffer underneath each other; you also have to explicitly specify when you want the data to be collected, which reduces the burden on the UA? `</hand waving>

**Comment by mpb** [comment]
I'll see what I can get in terms of numbers,
The user-space JS library we put together did exactly that; it let you
start and end a range, and get stats on activity during that range.

It would still be complicated to run multiple measurements in parallel.
Does the UA stick copies of renderTiming and compositeTiming events into
every active range? Does it just stick a single event into the timeline,
and let the various measures fight over it?

Also, two use cases it can't catch are a) time to first frame, where you
want to start measuring before your JS has a chance to run, and b)
smoothness of a scroll event where you want to catch from the beginning of
the action (maybe beforeScroll would help that use case?)

**Comment by igrigorik** [comment]
> It would still be complicated to run multiple measurements in parallel.
> Does the UA stick copies of renderTiming and compositeTiming events into
> every active range? Does it just stick a single event into the timeline,
> and let the various measures fight over it?

Assuming we resolve https://github.com/w3c/performance-timeline/issues/1, I guess this is solvable from client-land.. Client code can subscribe to the firehose and capture relevant ranges without interfering with anyone else. Under the hood, it can create copies, do on-the-fly processing, etc.

**Comment by vmpstr** [comment]
I think we agree that we're going with low-level primitives (at least initially). Can this we close this and reopen in the future when the need arises?

**Comment by igrigorik** [comment]
sgtm.
