### ISSUE TITLE
Interface and event naming

### ISSUE THREAD

**Issue by igrigorik** [WICG/frame-timing#12]
At TPAC, Simon (Apple) mentioned that...
- "CompositeTiming" sounds like we're compositing timing events
- "MainFrame" has other meanings in their implementation / is an ambiguous name

That said, we didn't come up with any better names at TPAC either. Thoughts, suggestions?

**Comment by paullewis** [comment]
Can Main become UI or Renderer? That's what it's called on other platforms, i.e. RendererFrame

For the composite timing name issue, how about following the model from the [Navigation Timing API](https://developer.mozilla.org/en-US/docs/Navigation_timing) and having distinct events:
- `performance.frame.rendererStart`
- `performance.frame.rendererEnd`
- `performance.frame.compositeStart`
- `performance.frame.compositeEnd`

Might be bonkers.

**Comment by paullewis** [comment]
Wait, that would need to be an array....

`performance.frames[0].rendererStart` etc.

**Comment by igrigorik** [comment]
@paullewis my understanding is that we can have multiple composite events associated with a single main frame event. As a result, we need to separate them out and use frameNumber for tracking the relationships. 

That aside... I like `RendererFrame`, except do we need `Frame` part at all? What if it was simplified it to `PerformanceRendererTiming`, `PerformanceCompositeTiming`?

/cc @mpb @natduca

**Comment by mithro** [comment]
@paullewis You can definitely have multiple composite events associated with a single main frame event and that is the reason why we need the sourceFrameNumber attribute (Issue #7 included a discussion about the topic.)

I personally don't really have any strong preference with having `Frame` in the name. My only two thoughts were;
- The duality of requestAnimation_Frame_ having PerformanceRenderer_Frame_Timing seems good form a consistency point of view.
- With `Frame` could be confusion between `<iframes>` and animation frames but that doesn't seem to have happened with requestAnimationFrame so it probably a non-issue.

**Comment by igrigorik** [comment]
Do we have any alternative ideas for `CompositeTiming`?

**Comment by mpb** [comment]
UITiming, CompositeTiming and DrawTiming are the three I can think of. They all have issues though. Composite sounds like the front runner.

**Comment by mithro** [comment]
I came up with the following ideas; `AsynchronousFrameTiming`, `OffThreadFrameTiming`, `ExternalFrameTiming` but don't really like any of them.

`PerformanceSynchronousRenderingFrameTiming`  and `PerformanceAsynchronousRenderingFrameTiming` is a pretty huge mouthful.

**Comment by paullewis** [comment]
I think we should roll with `PerformanceRendererTiming` and `PerformanceCompositeTiming`. A bit of a dumb question: would you get a hold of them like this?

``` javascript
var rendererEvents = window.performance.getEntriesByType("renderer");
var compositeThreadEvents = window.performance.getEntriesByType("composite");
```

If so, rad. If not, how?

**Comment by mpb** [comment]
SGTM. Yes, that's how you get access to them!

**Comment by igrigorik** [comment]
+1 to `RenderTiming` and `CompositeTiming`.. if someone comes up with a better name for the latter, we can revisit later.

**Comment by paullewis** [comment]
So removing the `Performance` bit from the front? I'm cool with that.

**Comment by igrigorik** [comment]
Doh, sorry.. No, I was lazy and didn't type it out. Performance bit should be there:
- `PerformanceRenderTiming`
- `PerformanceCompositeTiming`

**Comment by igrigorik** [comment]
@paullewis @mpb take a look at: https://github.com/w3c/frame-timing/commit/562c53001fa74e54e9a830091ac25fd554adca2c

Note that it's currently `PerformanceRenderTiming` not `PerformanceRendererTiming`... The former is shorter and consistent with `PerformanceCompositeTiming`. That said, if we want `Renderer`, then we should probably also update `Composite` to `Compositor` to be consistent.

WDYT? Personally, I'm good with `Render` and `Composite`.

**Comment by paullewis** [comment]
I'm fine with Render and Composite personally.

**Comment by mpb** [comment]
SGTM
