### ISSUE TITLE
Merging prediction with Frame Timings?

### ISSUE THREAD

**Issue by ashumeow** [WICG/frame-timing#16]
I read the <a href="http://updates.html5rocks.com/2014/11/frame-timing-api">article</a> and also, already read the <a href="http://w3c.github.io/frame-timing/">spec</a>.<br>
Currently, we use <a href="https://cloud.google.com/prediction/docs/getting-started">prediction</a> for data. So, how about for timings too? Along with prediction, we could add <a href="http://www.w3.org/TR/beacon/">beacon</a> too.<br>
What do you all think about it? (^_^)

**Comment by igrigorik** [comment]
As in, use ML to analyze and predict bad performance based some device/user signals, etc? Sure... But that's completely up to you and the application to handle. The purpose of the FT API is to provide access to the low-level data.

**Comment by ashumeow** [comment]
@igrigorik Machine learning is meant to analyze and get the data. I am not talking about getting or measuring the data based upon the bad performance. Well, Actually... Frame timing API comes under <a href="https://tools.ietf.org/html/rfc6455">web socket protocol</a>. The frames works under data-link layer that gets converted into bits and transmitted in the form of streams. I was trying to say about applying "prediction" by means of real-time event handler that might make it faster and also, i included "beacon" to add <a href="http://w3c.github.io/webappsec/specs/content-security-policy/"> security</a>, since one can do XSS attacks... Please do correct me if i am wrong. =)
