### ISSUE TITLE
Consider ~"Performance Observer" model instead of current buffer-based approach

### ISSUE THREAD

**Issue by natduca** [WICG/frame-timing#20]
I think we should consider frames as available only via performance-observers, and make this depend on that.

**Comment by natduca** [comment]
For now, lets assume that people wanting fps before "load" can't get it. Put a script tag in your head if you want it.

**Comment by mithro** [comment]
Could you explain the context here? I couldn't find anything on http://www.w3.org/TR/#tr_Web_Performance about "performance observers"?

**Comment by igrigorik** [comment]
@mithro we're still hashing it out, hence nothing official. That said, relevant background:
- https://github.com/w3c/performance-timeline/issues/1
- Latest discussions:
  - http://lists.w3.org/Archives/Public/public-web-perf/2014Dec/0016.html 
  - http://lists.w3.org/Archives/Public/public-web-perf/2014Dec/0021.html

**Comment by igrigorik** [comment]
(notes from a VC discussion today)

~"Performance Observers" or something similar to what is being currently discussed on the list feels like a much better mechanism for surfacing FT events. Current buffer based API is hard to work with and invasive (e.g. requires setting buffer size to 1 + periodically clearing it, which doesn't work well (if at all) when you have multiple parties interested in monitoring these events). 

Plan moving forward:
1. We're going to push the Observer discussion forward (it's a separate primitive).
2. For FT, we're leaving the buffer-based approach in the spec for now. Then, assuming we arrive at a good place with (1) (and in reasonable time), we will revisit the FT API and consider providing an observer-only implementation - aka, drop the buffer stuff entirely.

_P.S. We're leaving this bug open to track progress and related discussions._

**Comment by paulirish** [comment]
- WG feedback on PerfObserver in Jan:  https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0032.html
- PerformanceObserver overview document: https://docs.google.com/a/chromium.org/document/d/1fXtxtPC1Gg4PeLXI_axj6AvMTznf9X5lrj5HTyR3r3w/edit#heading=h.lmpa8rntu3jnl

**Comment by igrigorik** [comment]
Resolved via #48 - closing.
