### ISSUE TITLE
Where does time spent "prepainting" end up?

### ISSUE THREAD

**Issue by mithro** [WICG/frame-timing#23]
This may be a duplicate of https://github.com/w3c/frame-timing/issues/18 ? I'm unsure if something like "prepainting" falls into the "offscreen content" bit or not? @igrigorik feel free to close as a duplicate if you think it is.

If the browser decided to "prepaint" something (or do some other type of preparatory work), where does the cpuTime used end up? When prepainting is working correctly it should be significantly lowering the "time to render" a frame as most of the work has already been done before we even started.

It might be just a case of "this case is too complicated, we should ignore it now". It also doesn't seem all that useful to expose to the web developer as they don't really have much control over this, right? I could  imagine that we add a PerformancePrepaintTiming event in a V2 spec to cover this case.

@vmpstr - do you have any comments on this?

**Comment by vmpstr** [comment]
My interpretation is that for the main frame, we care about the work that we do in order to get a new frame on the screen. In that case, prepainting work is _not_ a part of this. Typically, we would do the work required for activation before doing prepainting.

**Comment by igrigorik** [comment]
Agreed with @vmpstr. Our primary goal (for v1 at least) is to communicate to the developer how much time they have left in their frame budget. If the UA uses some background tricks to raise the budget - e.g. prepainting, or some other super-clever optimization - so much the better, but that's an implementation detail I (as a developer) don't need to worry about.

I propose we skip/close this for now, and we can revisit in the future if there is demand for this sort of info.

**Comment by mithro** [comment]
If you guys are happy that it doesn't have a negative impact on the v1 use case then feel free to close and marked as defer to another specification or later version of this specification.

**Comment by igrigorik** [comment]
@mithro sg. closing, let's revisit later if necessary.
