### ISSUE TITLE
cost: sum of threads, or max time of threads?

### ISSUE THREAD

**Issue by vmpstr** [WICG/frame-timing#28]
This doesn't really have to go into the doc (or maybe it should?), but I want to reach an agreement on whether to use the sum of all threads' non-idle time, or max.

From my perspective, we should be using the sum of all threads involved in this work (ie, if we have 3 threads fully occupied to produce a frame in 16 ms, then we should report 48 ms as the cost). However, I know that people disagree. I think this captures the actual work done (like how much power is being utilized), but it doesn't provide an estimate of how much "room" there is before the 16ms budget. 

Wdyt?

**Comment by igrigorik** [comment]
> 3) cpuTime (now "cost") is not an OS-level CPU time, it continues counting if the thread is descheduled and is a MAX() not a SUM() of all concurrent threads processing (if there are more than one thread). This is intentional because as a web developer, you have some amount of resources to use and are trying to use them to achieve a desired effect (smoothly!) It is the kernel and the user agent's job to manage system resources, and distribute time fairly. - https://github.com/w3c/frame-timing/pull/22

I agree with @mpb on above. As a developer, I think it would be incredibly confusing to get a duration of 16ms and a cost that's 16ms+. Further, if cost is <16ms, it's impossible to distinguish if its just barely under 16ms and I have no budget left, or if you have four threads consuming 4ms each, and I actually have plenty of room left.

**Comment by vmpstr** [comment]
There are a couple of problems with the max approach:
- If say javascript takes 16ms, every frame, regardless of the frame, then information of how much rasterization work we do, or how much other work there is is completely lost, since we always report 16ms for cost.
- It's not clear what we report when work on one thread depends on work on the other thread. That is, if I have 16 threads and thread 1 does work from 0-1ms and schedules more work on thread 2, which does work from 1-2ms and schedules more work on thread 3, etc, so thread 16 does work from 15-16ms, then the max of all threads is 1ms, but if you add more work you will miss the frame. (Yes, this is an overly contrived example, but we have situations similar to this: we might schedule raster work late in the frame and it does 1ms worth of raster, just barely meeting 16ms budget, but we would report 1ms as cost).

**Comment by vmpstr** [comment]
Perhaps we need another field, something along the lines of "estimated time left until we miss a frame"? What I'm trying to say is that I think both pieces of information are important, but the term cost should capture all work IMHO. @natduca, wdyt?

**Comment by igrigorik** [comment]
> Perhaps we need another field, something along the lines of "estimated time left until we miss a frame"? 

I don't think we need another, what you're describing is, in fact.. what we're after - see use case (2) here: https://github.com/w3c/frame-timing/pull/22#issuecomment-67061014. As a web developer, I don't care how many threads are running, or how they're scheduling work between them (this is good to know for browser developers, but that's not the target audience for this API). Instead, I simply want to know if I'm within my 16ms budget, and how much headroom I have on each frame (or by how much I've exceeded it).

**Comment by mithro** [comment]
I think we should define cost as "duration minus _idle time not actively rendering_ for duration" and then define _idle time not actively rendering_ as "any time rendering work for _this_ frame is not running or blocked".

I think this definition has some nice properties;
- The time between finish rendering and starting the next frame is just another period of idle time.
- The case of doing the majority of work early and then doing a quick "fix up work" before delivery of the frame is just a frame with idle time in the middle.

With this definition any time **any** thread is doing rendering work (or currently suspended by the OS), you aren't idle. Multiple threads all doing rendering work at the same time ends up with the "max" type definition that @mbp likes.

You could think of it as being like the following almost Python code;

``` python
class RenderTimeCounter:
 def startFrame(self, t):
  self.startTime = t

 def startWork(self, t):
  self.rendering += 1
  # If rendering count is one, we are leaving an idle period and starting to
  # render stuff. Record the start time now.
  if self.rendering == 1:
   self.renderingPeriods.append({'start': t, 'end': None})

 def finishWork(self, t):
  self.rendering -= 1
  assert self.rendering >= 0
  # If nobody is rendering anymore then we are entering an idle period. Record
  # an end of the rendering time.
  if self.rendering == 0:
   assert self.renderingPeriods[-1]["end"] is None
   self.renderingPeriods[-1]["end"] = t

 def nextFrameStarting(self, t):
  assert self.rendering == 0
  assert self.renderingPeriods[-1]["end"] is not None
  self.endTime = t

 def getInfo(self):
  renderingFor = 0
  for work in workPeriods:
    renderingFor += work["end"] - work["start"]
  assert renderingFor < endTime - startTime
  return {"startTime": startTime, "duration": endTime - startTime, "cost": renderingFor}


class WorkerPool:
  class Worker:
    def run(self, stats):
      stats.startWork(Now())
      doStuff()
      stats.finishWork(Now())

  workers = [Worker(), Worker(), Worker()]

  def doFrame(self):
    # Get the frame time - as defined in the raf spec
    raftime = Now()

    # Finish the previous stats and send them to javascript
    self.last_frame_stats.nextFrameStarting(raftime)
    send_stats_to_javascript(self.last_frame_stats.getInfo())
    del self.last_frame_stats

    # Start a new stats
    stats = RenderTimeCounter()
    stats.startFrame(raftime)

    # Do synchronous javascript work
    stats.startWork(t)
    do_raf(raftime)
    stats.finishWork(t)

    # Do some multithreaded painting
    for w in self.workers:
      w.start()
    wait_for_all_to_finish(self.workers)

    # Sleep until we are close to frame deadline
    time.sleep(now - next_frame_time)

    # Do the final fix up rendering work
    stats.startWork(t)
    do_draw_and_swap()
    stats.finishWork(t)

    self.last_frame_stats = stats
```

**Comment by natduca** [comment]
Ilya, I understand this may be confusing, but it reflects reality. Sorry but thats the case. We can discuss mitigations using better naming, but the reality is there is the start, end and cost and they're independent of one another.

We must not specify which threads things run on. Different implementations run different parts of the pipeline on different threads. And some implementations [servo!] don't even in think in terms of threads.

Please use this: cost is sum of threads.

**Comment by igrigorik** [comment]
@mithro another :+1: from me - great stuff.

> This attribute must return a [High Resolution Time] with the difference between the `duration` and the idle time of the frame. The idle time is defined as any time rendering work for the current frame is not running or blocked.

WDYT? The "or blocked" may be redundant, I think we can drop it?

**Comment by igrigorik** [comment]
@natduca didn't see your reply as I was typing mine... 

I think we're talking about different use cases. I guess what Tim suggested (and my reply above) is what you're defining as "end time". Naming aside, the use case for it makes sense to me (see (2) in https://github.com/w3c/frame-timing/pull/22#issuecomment-67061014). 

What's the _developer_ use case for cost, if its defined as the sum of all threads?

**Comment by vmpstr** [comment]
IMO, the use case is a stable measure of how much work is being requested. Suppose the UA adds a new thread when there's sufficient work to almost miss 16ms budget, then as you consistently add more work, you'll see cost increase consistently. This is in contrast to the max/non-idle time where you would see work grow, then jump down, then grow again. &lt;/more very contrived cases&gt;

It might also be a good measure of power consumption on mobile (higher cost, higher battery drain).

This goes back to my earlier comment that I think both values are important... "cost of all work" and "time left until new frame" type of things. 

Note that @mithro's definition does not necessarily give you the time you have until you miss a frame. If there's idle time mid frame, it does not necessarily imply that you can give that much more work and still meet the budget... However, in practice, that's probably a good estimate.

**Comment by vmpstr** [comment]
To elaborate on my last paragraph there, I think @mithro's definition is in fact good for something like idleTime (during the frame), and I think we should use that.

**Comment by mpb** [comment]
So are you suggesting we report cost, idleTime and duration as 3 separate
items?
cost = sum of all threads
idleTime = time spent NOT working on any thread
duration = rafEndTime - rafStartTime?

Thanks,
-Mike

**Comment by vmpstr** [comment]
@mbp: Yep. This is what I am proposing:

duration = rafEndTime - rafStartTime
X = work as defined by @mithro 
idleTime = duration - X
cost = unrelated to above, sum of threads.

I have no preference on whether we report X or idleTime.

Basically, I think we want some notion of headroom left in a frame, at the same time we want a notion of total cost summed over all threads. We can't capture both of those in one variable.

Does that make sense? Is there problems with that (aside from coming up with wording)?

**Comment by vmpstr** [comment]
If there are no objections, I think the answer for this issue is that cost = sum of threads, and possibly adding a new field ( #31 )

**Comment by mpb** [comment]
I have no objection. Show of hands?

**Comment by mithro** [comment]
"sum of wall time for all threads doing work" (which I'll refer to as `cost`) has two really big issues. I'll try and enumerate them here;
- If you have 20 threads trying to do work on a single CPU machine, the `cost` is going to grow by 20 seconds for every second of time. This is even though there is only really 1 second of work being done for every second of time. This even occurs if 1 thread has a second of work to do and all the others only have 1 microsecond of work to do.
- What are the "units" of `cost`? It's in seconds of XXXX, but actually defining what XXXX is surprisingly hard. (Trying to define XXXX is what ended up with me discovering the above issue). It is kind of "wall seconds for work of a thread".
- The definition of `cost` is _extremely close_ to the definition of cpuTime. I'm sure people will see the "sum of work on threads" and straight away assume it is cpuTime and then become horribly confused.

**Comment by vmpstr** [comment]
That's fine, but as far as I know we don't have any definition of cpu time. Can we punt on using it and block on a different spec that adds a cpu time notion?

**Comment by mithro** [comment]
@vmpstr are you suggesting we just drop the `cost` attribute altogether? I think that would make the most sense if we aren't going to use cpuTime for the reasons I stated above.

**Comment by vmpstr** [comment]
What I meant to say is that we should use cost and have some wording of cost as a field. In parallel, we should proceed to spec cpu time.

Frankly I don't think there's a big issue with wall time in the interim. First, I don't think there are that many single core devices out there left (I might be totally mistaken on this). Second, I expect that most UAs out there have some consideration of how many threads they are spinning up vs how many threads of execution are available on the device (ie 20 threads on a single core machine is unlikely). All in all, wall clock time is probably going to be a close enough approximation _for now_.

To your second point, I think the units of cost are milliseconds. If using cpu time, this is the amount of time each thread was running summed over threads. If using wall time, this is the amount of time each thread _had work scheduled_ summed over threads.

If you disagree or if you feel that we _have to_ use cpu time or nothing at all, then yes, I think the only option left is removing this from the spec altogether until we have a notion of cpu time available. In that case we're really left with startTime and duration (which is a multiple of 16ms).

**Comment by mithro** [comment]
@vmpstr - This problem occurs even if Chrome only has 2 threads on a 4 core machine if the OS chooses to only schedule non-Chrome tasks on 3 of the cores.

Chrome has _way_ more threads than cores with things like Impl side painting. You have the main and impl, then the impl workers, then the io thread -- all per render, and then there are also the browser threads and the GPU thread and......

We are left with startTime, duration and idle time. Idle time is still fine in these cases.

**Comment by vmpstr** [comment]
Idle time is also a flawed measure, since the only thing it can indicate to you is how much time was idle during the particular run time configuration of the system. If you have idle time if 0ms, then you would expect that adding more work would cause to you miss a frame. However, that doesn't have to be true if for instance UA spins up another thread, or if OS gives you one more core.

So, yes we can report on idle time during that particular frame while having some configuration, but that's information that isn't actionable in any way (unless of course I'm missing something).

As @igrigorik and @mbp mention in the doc (which also documents the cons of idleTime), if we have cost / (refresh interval \* peak concurrency), then we might get a normalized estimate of system utilization.

**Comment by igrigorik** [comment]
Let me try a take a different approach here... As a developer I want to know:
1. relative cost of the frame (e.g. optimizing for power efficiency)
   - can be captured via sum of the cpu times for each task. Correct?
   - this is (likely) a more general concept and is independent of FT.
2. how much more work could I have thrown at the UA before I would miss the frame budget?

(2) is the tricky one. Power management makes this a moving target, and even the UA could implement some crazy strategies to hit the frame budget while keeping the idle time low - e.g. don't wake extra cores, let processing run on fewer cores and at reduced clock-rate, or some such.. Resulting in low "idle time" but plenty of spare capacity where more more _could_ have been done. Right?

In light of that.. is there any way to provide an estimate (even if its rough) for amount of "head room" we had in the system? I guess we'd have to assume the optimistic case of "if we maxed out all available resources across our workers and at maximum speed, then we would have had....". But, even that seems like a really hand-wavy number since I have no idea how often that'd be true on a real-world device. Thoughts? How can we (if at all) give developers guidance on this?

**Comment by mithro** [comment]
To save power you want a _large_ idle time, not a _small_ idle time. Idle
time is when the CPU can be in a deep sleep state and thus consume minimal
power.

This is called "race to idle" and how everything has worked for the last 10
years and only now changing slightly with ARM introduced the big/small
architecture.

**Comment by vmpstr** [comment]
If work can be done one one core in 15ms, isn't that less power than waking up 15 cores to do 1ms of work each?

(not to be confused with reducing the frequency of a single core to fill up 15 ms vs doing 1ms on one core)

**Comment by vmpstr** [comment]
As for @igrigorik's point (2), I think that's a really good way of putting it. If we phrase the requirement as "how much more work can I give the UA and still meet my budget" then it becomes evident that idle time is not answering this. Idle time is saying "how much more work I could have done _with the configuration of the system as it was at that time_". Also, I completely agree that with power management and different UA implementations, the "configuration of the system" can change frame to frame, thus making idle time an interesting, but ultimately meaningless measure.

(All I'm trying to say is that a dev seeing 5ms of idle time and 16ms duration is far more likely to misinterpret what that 5ms means without any further knowledge of cores/threads/concurrency within the UA)

**Comment by mithro** [comment]
@vmpstr, on an x86 system (since the Pentium-M days) it is almost always
better to wake up 15 cores for 1ms each then run one core for 15ms. It
turns out that there is a minimum power requirement to have a single core
not in deep sleep which is normally much higher than the incremental cost
of turn each core.

This effect is even more amplified by other things in the system, for
example when all cores are power down you can put the RAM in low power
state too. Even one core being awake means that you can't do this to the
RAM.

The one case that exists currently that I know about is the "BigSmall"
architecture (that ARM is currently experimenting with). This is where not
all the cores in a CPU are created equal. One core is design to be
significantly lower power (at a significant decrease in performance). You
then power off all the high performance cores and just leave the slow core
running. This has benefits for systems which need to do a small amount of
work very frequently. Even in this architecture you get the absolute best
power saving when all cores are in deep sleep because again you can turn
off other things like the RAM. Linux doesn't really have great support for
this architecture yet.

**Comment by igrigorik** [comment]
Closing, summary doc + further discussion: http://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0019.html
