### ISSUE TITLE
Capturing frame duration, omit zero values?

### ISSUE THREAD

**Issue by igrigorik** [WICG/frame-timing#3]
> nduca@: why cpuTime vs duration. When you look at frames, they're delimited by rAF. So, you'd intuitively think that if you had raf at ts=0 and ts=16, then duration of frame0 is 16. But all our browsers are threaded, so really a frame might begin at ts=0 but on other threads keep doing another 30+ms of work. Maybe we should spec duration as the obvious time since last raf, eg 16 in above, but have something we bikeshed to mean "cost of this frame."

`PerformanceCompositeTiming` is set to (always) provide 0 for `duration`, which is a bit confusing and seems unnecessary. Should we instead expose duration as a special variable on `PerformanceMainFrameTiming` and omit it on the CompositeTiming event? Alternatively, is there a cleaner way to handle this case? It would be nice to keep both events consistent.

**Comment by mithro** [comment]
There are a couple of cases for which "duration" of a frame might be useful (or broken?). These cases might be rare / unusual enough that not thinking to much about them is fine.
- In a pipelined or parallel system which allows multiple frames to be rendered at once then the duration could be longer than raf but everything still be fine.
- gsync / adaptive sync and other non-vsync driven displays. The duration is going to be all over the place here.
- dynamic shifting between vsync frequency multiples. For example, rendering on a 120Hz device, you might want to render at 120fps during user interaction and 60fps otherwise.

**Comment by natduca** [comment]
Duration without a specific qualifier is meaningless because it has myriad interpretations. So my theory is we want to avoid  using that field at all... ideally we woudln't have it, but to be part of the getEntries timeline, we have to have to subclass the performance timing class which requires us to have a field. Hence zero.

If we ever decide to expose one particular aspect of time that a given onscreen frame, we can add more fields if needed.

**Comment by mithro** [comment]
The PerformanceEntry specification at http://www.w3.org/TR/performance-timeline/#performanceentry explicitly says;

<blockquote>
A performance metric may choose to return a duration of 0, if the duration concept doesn't apply.
</blockquote>

So setting this to zero seems like the right solution?

**Comment by igrigorik** [comment]
- composite should say 0 
- mainframe should capture start of current minus start previous frame

**Comment by mithro** [comment]
@igrigorik sounds like the proposal is thisMainFrame.duration == lastMainFrame.startTime - thisMainFrame.startTime? Is there a case where this wouldn't hold?

I don't know enough about w3c specs to know if this duplication is okay or preferred?

**Comment by mpb** [comment]
Yes, that's the proposal. Anyone else care to chime in on preference from a w3c perspective?

**Comment by igrigorik** [comment]
@mithro short of the very first frame, which would be from navigationStart [1], I can't think of any other cases? I don't think we're duplicating anything here.. we can't guarantee that you will always have access to a previous frame (e.g. full buffer, cleared buffer, etc), so doing some basic book keeping for the user is valid.

[1] https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming/Overview.html#dom-performancetiming-navigationstart

**Comment by mithro** [comment]
If everyone else is happy, then sounds good to me.

**Comment by mpb** [comment]
Please take a look, does pull #15 sound correct?
Thanks.

**Comment by igrigorik** [comment]
Wait, wouldn't that give you the duration of last frame, not the current frame? In fact, re-reading our previous wording:

> "The duration attribute will return a DOMHighResTimeStamp with the duration of the frame, computed by subtracting the startTime of the next frame from startTime of the current frame."

I think that's what we want, and it covers both the first and all subsequent frames correctly? Perhaps we should just keep that?

**Comment by mpb** [comment]
Do we know the start time of the next frame?

**Comment by igrigorik** [comment]
@mpb woops, you're right, I think that should read...

> The duration attribute will return a DOMHighResTimeStamp with the duration of the frame, computed by subtracting the startTime of the frame from startTime of the next frame in sequence.

We're emitting the frame event after it has finished, which means we're already on the next frame, correct? As in, "endTime of current frame == startTime of next frame".

**Comment by vmpstr** [comment]
How would we deal with idle (no main frames) scenarios?

Something like raf, wait for a second, raf again. Would that mean that the frame duration reported would be 1s? I think that would make duration very much dependent on user interaction with the page, no?

**Comment by igrigorik** [comment]
Based on our last discussion, I think the intent was to have `duration` report the time from last vsync (@mpb had the exact language, I'll defer to him), to address the exact case you're describing -- i.e. don't rely on previous frame.

**Comment by mithro** [comment]
The discussion in this issue directly conflicts with the discussion in #1. We seem to have two definitions for duration now?

**Comment by mpb** [comment]
Yes.. lets try and consolidate the discussion to #1.  Between that, this and #22 there are a few conflicting stories. 
I believe there is a deadline for getting FPWDs out before year-end, and I think the duration/cpuTime clarification is the only outstanding issue, for what it's worth.

**Comment by igrigorik** [comment]
Let's continue the discussion in #22 - closing this.
