### ISSUE TITLE
Should we have an `endTime` property (and then define `duration` in terms of it)

### ISSUE THREAD

**Issue by mithro** [WICG/frame-timing#30]
In https://github.com/w3c/frame-timing/issues/29 I suggested a way to define duration by talking about an "end time" of the frame.

Does it  make sense for us to define an `endTime` property (which should be a raf value, assuming a raf would have been called)? The property doesn't actually have to be exposed to javascript but I think it makes the spec easier to understand.

With an `endTime` property `duration` then just becomes the simple definition of `endTime` - `startTime`.

@igrigorik

**Comment by igrigorik** [comment]
I don't think we should expose endTime as an additional attribute.. we have multiple endTime's - e.g. does it include or exclude idle time, and all that fun stuff. 

I think we can reference it + define it as part of duration: https://github.com/w3c/frame-timing/issues/29#issuecomment-67205090 - does that work?

**Comment by mithro** [comment]
I'm suggesting we define endTime as a **concept** in the specification that we can then use in the definitions of other values. I think this will make the spec easier to read and understand.

As mentioned, I don't think it makes much sense to expose this to javascript.

**Comment by mpb** [comment]
I think that is reasonable. End time language has been added in #29, lets follow up there.
