### ISSUE TITLE
onframetimingbufferfull should be EventHandler

### ISSUE THREAD

**Issue by foolip** [WICG/frame-timing#33]
In http://w3c.github.io/frame-timing/#extensions-performance-interface

Compare with https://w3c.github.io/resource-timing/#extensions-performance-interface

Maybe the idea here is to avoid events, but Performance isn't a Node so there won't be time wasted in calculating the event path or anything like that...

(Maybe fix the indentation too)

**Comment by mpb** [comment]
The indentation is a product of ReSpec http://www.w3.org/respec/ (couldn't really tell you why) but I'll fix the event type. Thanks.
