### ISSUE TITLE
What does PerformanceCompositeTiming measure?

### ISSUE THREAD

**Issue by igrigorik** [WICG/frame-timing#35]
We should clarify what it measures and how it relates to PerformanceRenderTiming. A brief explanation in the [intro paragraph](http://w3c.github.io/frame-timing/#introduction-1) would do the trick.

**Comment by igrigorik** [comment]
Iterating on a draft by @mpb, how about...

---

The `PerformanceRenderTiming` and `PerformanceCompositeTiming` interfaces, and extensions to the Performance interface, enable web developers to measure the performance of their applications by giving them access to frame performance data to facilitate smoothness (i.e. Frames per Second and Time to Frame) measurements:
- `PerformanceRenderTiming` captures the work performed by the renderer to process the frame: DOM modification, JavaScript processing, CSS computations, and similar activities.
- `PerformanceCompositeTiming` captures events performed by the compositor to place rendered content onto the screen.

The relationship between `PerformanceRenderTiming` and `PerformanceCompositeTiming` might vary based on the architecture of the user agent. For example, if there is no separation between rendering and compositing, there may be a 1:1 mapping of `PerformanceRenderTiming` and `PerformanceCompositeTiming` events. If the architecture supports CSS animations or composite thread scrolling, there may be many `PerformanceCompositeTiming` events corresponding to a single `PerformanceRenderTiming` event.

**Comment by mpb** [comment]
Sounds good to me.

**Comment by natduca** [comment]
Sounds good too. Might have some explanatory text in the tailout on why a
browser typically has N composites to 1 frame, and that its very common
that its not 1:1... as written, it sounds like its idiosyncratic browsers
that have divergent counts here.

**Comment by igrigorik** [comment]
Wordsmithing... how about:

The relationship between `PerformanceRenderTiming` and `PerformanceCompositeTiming` events will vary based on the workload, and architecture and configuration of the user agent. For example, the user agent may report many `PerformanceCompositeTiming` events corresponding to a single `PerformanceRenderTiming` event due to a CSS animation, composite thread scrolling, or similar activities. Other workloads may result in 1:1 mapping of `PerformanceRenderTiming` and `PerformanceCompositeTiming` events, and the exact relationship is also subject to user agent architecture and configuration.

**Comment by natduca** [comment]
Sounds great

**Comment by igrigorik** [comment]
@natduca @mpb live @ http://w3c.github.io/frame-timing/#introduction-1

I'm wondering if that's enough though? The intro is a non-normative section. Should we also provide some concrete guidance for when each type of event should be delivered within the interface definitions?

**Comment by natduca** [comment]
Not sure! Lets maybe get further along so we can dogfood and then see what
we learn?

**Comment by igrigorik** [comment]
sg, closing this. @mpb will open a new bug for tracking progress on a processing section / algorithm.
