### ISSUE TITLE
Support for independent components?

### ISSUE THREAD

**Issue by RByers** [WICG/frame-timing#36]
If this API becomes popular and frameworks like jQuery start using it, won't there be problems with multiple components requesting the entries and clearing them?  This seems like it could become a major source of pain in practice.

The whole PerformanceTimeline concept seems to work only for data that's small enough to hang around for the life of the page.  An alternative would be for a client to request a timeline object that's a view into the global timeline.  Then you could clear just your view.  You wouldn't have a way to request entries prior to the time you requested your view.

**Comment by natduca** [comment]
It sounds like you're looking for PerformanceObservers.... 

https://lists.w3.org/Archives/Public/public-web-perf/2015Feb/0013.html

**Comment by igrigorik** [comment]
+1.. that's the exact problem we're trying to solve with PerformanceObserver.

**Comment by igrigorik** [comment]
@RByers closing, feel free to reopen if you think PerfObservers are not sufficient.

**Comment by RByers** [comment]
Yes, sorry - Nat and I talked and agreed we were already on the same page.
