### ISSUE TITLE
PerformanceCompositeTiming isn't well defined

### ISSUE THREAD

**Issue by toddreifsteck** [WICG/frame-timing#37]
It isn't 100% obvious what the cross-platform intent of PerformanceCompositeTiming is. It seems to encompass the concept of anything that is NOT on the UI thread that slows down display. We should probably come up with a more cross-architecture name and definition for this.

**Comment by toddreifsteck** [comment]
Another option is to cut PerformanceCompositeTiming from initial spec

**Comment by igrigorik** [comment]
@toddreifsteck it's not "slows down display", as much as it is: work has been handed off to compositor (e.g. CSS animations) and we need visibility into that part of the system to deliver on our promise of enabling RUM frame timing measurements. Omitting this would be a serious limitation to this API.

That said, the current spec **is** missing a processing section that defines the above relationship and the steps for when such events should be emitted... @mpb is working on a draft for that and I'm hoping we'll have a first cut within the next week or so; I'm hoping that'll address the above concerns.

**Comment by igrigorik** [comment]
@toddreifsteck as per https://lists.w3.org/Archives/Public/public-web-perf/2015May/0001.html.. Does that resolve the issue in this bug? Can we close this?

**Comment by toddreifsteck** [comment]
I believe we should keep this issue open until the processing model update is in. At that point, this spec should be updated to point to those sections and this issue can be closed.

**Comment by igrigorik** [comment]
No longer relevant, see #48 - closing.
