### ISSUE TITLE
Polyfill is out of date re latest spec changes

### ISSUE THREAD

**Issue by natduca** [WICG/frame-timing#38]
Events have changed names.
Performance Observers exists.

**Comment by igrigorik** [comment]
Is this still relevant? As in, is the current API behavior reasonably polyfillable? Do we want to keep this open? /cc @mpb

**Comment by mpb** [comment]
I think we should definitely revisit this. In like of PerformanceObserver, we can get rid of the setBufferSize(1) funny business at the very least. I think the rest of it is still reasonable though, in theory.

**Comment by igrigorik** [comment]
@mpb you'd still need fallback to setBufferSize for those that don't implement PerformanceObserver.

**Comment by igrigorik** [comment]
Let's track this on the polyfill repo. Opened https://github.com/GoogleChrome/frame-timing-polyfill/issues/21, closing this issue.
