### ISSUE TITLE
setFrameTimingBufferSize should queue a task to fire the buffer full event

### ISSUE THREAD

**Issue by esprehn** [WICG/frame-timing#41]
Currently the event fires inside the setFrameTimingBufferSize method, it should fire async instead.

setResourceTimingBufferSize should be changed to fire the event async as well.

**Comment by esprehn** [comment]
Specifically this spec should change:

"""
onframetimingbufferfull of type EventHandler,
The event handler for the frametimingbufferfull event. Immediately after the buffer used to store the list of PerformanceRenderTiming and PerformanceCompositeTiming resources becomes full, the User Agent must fire a simple event named frametimingbufferfull that bubbles, isn't cancelable, has no default action, at the Performance object [Navigation-Timing-2].
"""

we should queue a task.

**Comment by igrigorik** [comment]
FWIW, the plan is to rip out buffer stuff and be PerfObserver only: https://github.com/w3c/frame-timing/issues/20. As a result, I think this is a noop?

**Comment by igrigorik** [comment]
No longer relevant, see #48 - closing.
