### ISSUE TITLE
ambiguous 'name' attribute 

### ISSUE THREAD

**Issue by hiikezoe** [WICG/frame-timing#42]
"This attribute MUST return the name of the requesting document. "
This description is not clear to me. The document URI is used in current Chrome implementation, and will be used in Firefox. The description should make it clear.

**Comment by igrigorik** [comment]
Perhaps: "This attribute MUST return the [current document's address](http://www.w3.org/TR/html5/dom.html#the-document's-address)" ...?

**Comment by hiikezoe** [comment]
Sounds good to me.

**Comment by igrigorik** [comment]
@mpb any objections?

**Comment by mpb** [comment]
No objections from me!

**Comment by igrigorik** [comment]
@plehegar @toddreifsteck any thoughts on this one?

**Comment by toddreifsteck** [comment]
LGTM
