### ISSUE TITLE
Add links to implementation status bugs for browsers.

### ISSUE THREAD

**Issue by mithro** [WICG/frame-timing#43]
It would be good to link to the implementation bugs in Chrome, Firefox, etc. This would probably be more for the explainer / README rather then the spec itself. That way people can get an idea of how / when they can use the stuff mentioned here.

**Comment by mithro** [comment]
BTW - I pinged the Chrome bugs the other day and wasn't able to get a clear idea where the Chrome implementation was at. I work on Chrome and helped with the spec yet couldn't figure out what was going on, so I can't imagine what external feel.

**Comment by plehegar** [comment]
@mithro got those links handy somewhere? I'm happy to add them.

**Comment by mpb** [comment]
Is https://code.google.com/p/chromium/issues/detail?id=444122 the one you are looking for?

**Comment by igrigorik** [comment]
FWIW, for Chrome a better place to link to is https://www.chromestatus.com/feature/5558926443544576. 
- IE dashboard: https://status.modern.ie/?term=timing - no mention of FT yet :( /cc @toddreifsteck 
- Mozilla recently launched an effort to implement a dashboard as well..

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar popping up a level.. None of our specs link out to implementation updates, and I don't think that's the right place to track that either. On the other hand, it _would_ be convenient to have a link to a "status" page for each browser -- perhaps something we should place in readme's for each spec?

**Comment by plehegar** [comment]
Did you see what I started for Page Visibility? I added an "Implementation" header at the top. Happy to refine the idea.
http://w3c.github.io/page-visibility/
