### ISSUE TITLE
PerformanceCompositeTiming's name is oddly spec'ed

### ISSUE THREAD

**Issue by smaug----** [WICG/frame-timing#45]
[name]
  "This attribute MUST return the name of the requesting document. "

What is " the name of the requesting document" ? I don't see that spec'ed anywhere.
Also, PerformanceRenderTiming's name is current document's address. 
Why the difference?

**Comment by hiikezoe** [comment]
The change has been missed in #42.

**Comment by igrigorik** [comment]
No longer relevant, see #48 - closing.
