### ISSUE TITLE
Use some generic Performance*Timing interface for both Render and Composite?

### ISSUE THREAD

**Issue by smaug----** [WICG/frame-timing#46]
Do we really need a separate interface for both cases? Could we perhaps just use the same
interface for render and composite. I could imagine there to be also other timing stuff where a counter is needed.

Perhaps something like
interface CountedPerformanceTiming : : PerformanceEntry {
    readonly attribute unsigned long count;
    serializer = {inherit, attribute};
};

**Comment by igrigorik** [comment]
What's the downside to keeping them separate?

**Comment by toddreifsteck** [comment]
Per 8/12 W3C call, we can add this in the future if a need beyond the first two entries arises. Please re-open if there is a strong reason to address this before that point.
