### ISSUE TITLE
Sync interface name for the entry object

### ISSUE THREAD

**Issue by plehegar** [WICG/frame-timing#49]
Frame uses "PerformanceFrameTimingEntry" for the interface. But NT, RT and UT don't use "Entry", eg "PerformanceResourceTiming", etc.

**Comment by igrigorik** [comment]
Heh, I "fixed" that right before I sent the earlier pull.. @mpb any objections? Shorter is better in my books.

**Comment by mpb** [comment]
No objections here!

**Comment by igrigorik** [comment]
Fixed in https://github.com/w3c/frame-timing/commit/99f77d33289f14737b4d956b058183aed30ef19e.
