### ISSUE TITLE
The example in the W3C Site for the http://www.w3.org/TR/frame-timing/ is not well formed

### ISSUE THREAD

**Issue by GianlucaValerio** [WICG/frame-timing#52]
Ciao, the example html presented in the page http://www.w3.org/TR/frame-timing/ seems that has lost one "}".

var observer = new PerformanceObserver(function(list) {
    var perfEntries = list.getEntries();
    for (var i = 0; i < perfEntries.length; i++) {
       console.log("Uh oh, slow frame: ", perfEntries[i]);
      } // close the for loop
    }); // close the PerformanceObserver object
  observer.observe({entryTypes: ['frame']});

Regards
Gianluca

**Comment by plehegar** [comment]
Fixed in
 https://github.com/w3c/frame-timing/commit/660fef60581365548792cabf04c0fbdfc4fb6e99
Thank you!
