### ISSUE TITLE
sourceFrameNumber attribute can be null breaks correlating with PerformanceCompositeTiming

### ISSUE THREAD

**Issue by mithro** [WICG/frame-timing#7]
The sourceFrameNumber attribute is the only method of correlating PerformanceCompositeTiming to PerformanceMainFrameTiming. If it is allowed to be null then doesn't PerformanceCompositeTiming objects become useless?

Maybe it should only be allowed to be null when PerformanceCompositeTiming support is not provided / enabled?

**Comment by natduca** [comment]
Can someone clarify why we allow it to be null?

**Comment by mpb** [comment]
That was based on some specific feedback, to accommodate browser vendors who might not be able to associate every composite event with a source frame. I'm fine removing that caveat.

**Comment by igrigorik** [comment]
- in Chrome we always have the sourceFrameNumber
- AI: get FF and IE feedback on this bug: is this a case where you may sometimes have it, never have it, or always have it?

**Comment by mattwoodrow** [comment]
We (Mozilla) won't necessarily have a corresponding main-thread frame for each compositor frame, because we can run animations/video/scrolling asynchronously.

It looks like the current spec allows the sourceFrameNumber to be null for PerformanceMainFrameTiming, but not for PerformanceCompositeTiming. 

It seems like this should be the reverse, all main-thread frames should get a frame number, but not all composites correspond to one of those frames.

**Comment by mithro** [comment]
The point of the sourceFrameNumber is to associate synchronous frames (main-thread frames) and asynchronous frames (compositor thread frames) together.

In your asynchronous animation/video/scrolling case you should be using the frame number of main frame which generated the information you are using for the asynchronous event. It's perfectly fine to have many compositor frames associated with a single main frame (and the explainer document goes through the cases where this might happen). Can you explain a case where there wouldn't be a main frame associated with compositor frames?

The javascript example code in [Calculating Smoothness](https://github.com/w3c/frame-timing/wiki/Explainer#calculating-smoothness) is dependent on being able to map every compositor frame back to main frame.

**Comment by mattwoodrow** [comment]
Ok, so for composites that happen without main-thread input then the 'main frame which generated the information' is just the most recent main-thread frame we've received. We can definitely return that.

**Comment by mithro** [comment]
@mattwoodrow correct. Is there a way we could update the specification document to make that idea clearer for you?

**Comment by mattwoodrow** [comment]
I just checked the spec wording and it's pretty clear, sorry for the sidetrack.

Making sourceFrameNumber required for PerformanceMainThreadTiming seems like the right thing to do.

**Comment by mpb** [comment]
Ok, I will remove the 'optional' wording and leave as-is.
Thanks!

**Comment by mpb** [comment]
Updated in pull request #13

**Comment by mithro** [comment]
@mpb From a commit history point of view it would be good if "removal of optional wording" change could be separate from the conversion to ReSPEC. Either a separate commit before or after would work. At the moment it is really hard to see if this change happened in the commit history.

**Comment by mpb** [comment]
Fair enough. #14 has this change, now.
