### ISSUE TITLE
Unclear about the startTime attribute on PerformanceMainFrameTiming object

### ISSUE THREAD

**Issue by mithro** [WICG/frame-timing#9]
The startTime attribute on PerformanceMainFrameTiming object currently says,

<blockquote>
The startTime attribute will return a DOMHighResTimeStamp with current frame's beginning time value [High Resolution Time].
</blockquote>

Does it mean;
- The time we started doing rendering on the main thread (which could be well after any vsync signal).
- The last vsync time.
- The time used to populate the animations engine.
- Something else I didn't consider.

The middle two options have issues around what happens when a browser might be rendering for a time other than the last vsync time which could occur for many different reasons (For example, pre-rendering, pipelining multiple frames, rendering in the background or rendering for the time that things will actually hit the displays glass).

For the last two options the value should probably be related to to the value given to javascript requestAnimationFrame? If so, could that be explicitly stated?

**Comment by natduca** [comment]
"frames beginning time value" should be the time passed into all the requestAnimationFrame callbacks as the frame beginning time. I believe the rAF spec gives enough details on the processing model for this to be precise but if its not lets make sure we tighten the language. We want this to be the start of rAF for the frame though. Hence, in the list of 4 that you give, its the "what you didn't consider."

**Comment by mithro** [comment]
Is knowing the time "rendering" started in the main thread as opposed to the rAF time useful at all? Providing cpuTime seem to cover all the use cases that such a distinction would provide so using rAF here seems **perfectly reasonable**.

Explicit wording around the startTime's relationship to the rAF value seems like a good idea (so nobody accidently uses a different value).

**Comment by mpb** [comment]
so

<blockquote>
 The startTime attribute will return a DOMHighResTimeStamp with current frame's beginning time value (identical to the frame beginning time used for requestAnimationFrame callbacks) [High Resolution Time] [RequestAnimationFrame].
</blockquote>

and a link to 
https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/RequestAnimationFrame/Overview.html#processingmodel

in the references section?

**Comment by mithro** [comment]
Sounds good to me! Anyone else?

**Comment by igrigorik** [comment]
- Nat: all good, update.

**Comment by mithro** [comment]
Created a pull request #10 with changes as suggested. Feel free to reword / rework the request (or just add comments asking for them) if you feel there could be improvements to it.

**Comment by mpb** [comment]
Looks good to me!
If anyone else sees any issues, feel free to re-open.
